//! Stable diagnostic codes emitted by the diagnostics engine.
//!
//! Codes are Graphene-owned identifiers; hosts localize them without parsing English text.

pub(crate) const JVM_OUT_OF_MEMORY: &str = "DIAGNOSTIC_JVM_OUT_OF_MEMORY";
pub(crate) const JAVA_CLASS_VERSION_MISMATCH: &str = "DIAGNOSTIC_JAVA_CLASS_VERSION_MISMATCH";
pub(crate) const CLASS_LOADING_FAILURE: &str = "DIAGNOSTIC_CLASS_LOADING_FAILURE";
pub(crate) const LOADER_MISSING_DEPENDENCY: &str = "DIAGNOSTIC_LOADER_MISSING_DEPENDENCY";
pub(crate) const DUPLICATE_MOD_ID: &str = "DIAGNOSTIC_DUPLICATE_MOD_ID";
pub(crate) const LOADER_LOAD_FAILURE: &str = "DIAGNOSTIC_LOADER_LOAD_FAILURE";
pub(crate) const MIXIN_FAILURE: &str = "DIAGNOSTIC_MIXIN_FAILURE";
pub(crate) const NATIVE_LIBRARY_FAILURE: &str = "DIAGNOSTIC_NATIVE_LIBRARY_FAILURE";
pub(crate) const GRAPHICS_INITIALIZATION_FAILURE: &str =
    "DIAGNOSTIC_GRAPHICS_INITIALIZATION_FAILURE";
pub(crate) const JVM_FATAL_ERROR: &str = "DIAGNOSTIC_JVM_FATAL_ERROR";
pub(crate) const PROCESS_EXIT_NONZERO: &str = "DIAGNOSTIC_PROCESS_EXIT_NONZERO";
pub(crate) const CAUSE_UNDETERMINED: &str = "DIAGNOSTIC_CAUSE_UNDETERMINED";

// Instance verification correlation codes.
pub(crate) const INSTANCE_DESCRIPTOR_INVALID: &str = "DIAGNOSTIC_INSTANCE_DESCRIPTOR_INVALID";
pub(crate) const INSTALL_RECEIPT_INVALID: &str = "DIAGNOSTIC_INSTALL_RECEIPT_INVALID";
pub(crate) const LOCKFILE_MISSING: &str = "DIAGNOSTIC_LOCKFILE_MISSING";
pub(crate) const LOCKFILE_INVALID: &str = "DIAGNOSTIC_LOCKFILE_INVALID";
pub(crate) const INSTANCE_IDENTITY_MISMATCH: &str = "DIAGNOSTIC_INSTANCE_IDENTITY_MISMATCH";
pub(crate) const MANAGED_FILE_MISSING: &str = "DIAGNOSTIC_MANAGED_FILE_MISSING";
pub(crate) const MANAGED_FILE_WRONG_TYPE: &str = "DIAGNOSTIC_MANAGED_FILE_WRONG_TYPE";
pub(crate) const MANAGED_FILE_SIZE_MISMATCH: &str = "DIAGNOSTIC_MANAGED_FILE_SIZE_MISMATCH";
pub(crate) const MANAGED_FILE_HASH_MISMATCH: &str = "DIAGNOSTIC_MANAGED_FILE_HASH_MISMATCH";
pub(crate) const GENERATED_OUTPUT_MISSING: &str = "DIAGNOSTIC_GENERATED_OUTPUT_MISSING";
pub(crate) const GENERATED_OUTPUT_MISMATCH: &str = "DIAGNOSTIC_GENERATED_OUTPUT_MISMATCH";
pub(crate) const NATIVE_DIRECTORY_MISSING: &str = "DIAGNOSTIC_NATIVE_DIRECTORY_MISSING";
pub(crate) const UNSAFE_SYMLINK: &str = "DIAGNOSTIC_UNSAFE_SYMLINK";
pub(crate) const LEGACY_DESIRED_STATE: &str = "DIAGNOSTIC_LEGACY_DESIRED_STATE";
pub(crate) const REPAIR_SOURCE_UNAVAILABLE: &str = "DIAGNOSTIC_REPAIR_SOURCE_UNAVAILABLE";
pub(crate) const REPAIR_CONFLICT: &str = "DIAGNOSTIC_REPAIR_CONFLICT";

// Offline content/mod correlation codes.
pub(crate) const MALFORMED_MOD_ARCHIVE: &str = "DIAGNOSTIC_MALFORMED_MOD_ARCHIVE";
pub(crate) const MISSING_REQUIRED_DEPENDENCY: &str = "DIAGNOSTIC_MISSING_REQUIRED_DEPENDENCY";
pub(crate) const CONTENT_INCOMPATIBILITY: &str = "DIAGNOSTIC_CONTENT_INCOMPATIBILITY";
pub(crate) const LOADER_ENVIRONMENT_MISMATCH: &str = "DIAGNOSTIC_LOADER_ENVIRONMENT_MISMATCH";

// Java/runtime correlation codes.
pub(crate) const JAVA_PROBE_FAILED: &str = "DIAGNOSTIC_JAVA_PROBE_FAILED";
