[package]
name = "graphene-service"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
graphene-core.workspace = true
graphene-auth.workspace = true
graphene-platform.workspace = true
graphene-network.workspace = true
graphene-storage.workspace = true
tokio.workspace = true
tracing.workspace = true
graphene-minecraft.workspace = true
graphene-instance.workspace = true
graphene-java.workspace = true
graphene-providers.workspace = true
graphene-install.workspace = true
graphene-launch.workspace = true
serde_json.workspace = true
